### ISSUE TITLE
Versioned Releases

### ISSUE THREAD

**Issue by TisRyno** [MyUNiDAYS/unidays-php#15]
Hi, me again.

Can we please get tagged releases.
This code is going to be pulled into a production environment in which we are getting hundreds of orders a day, every deployment we make updates the composer components potentially.

I can see a scenario in which a bug is introduced and because we can only pull using `dev-master` this bug would immediately be pulled into our production environment if employees did not notice/test properly.

Thanks.

**Comment by jimgolfgti** [comment]
As you wished, please see https://packagist.org/packages/unidays/unidays-php#v1.2.0
