### ISSUE TITLE
Higher values than 999.99 don't work because of double number_format call

### ISSUE THREAD

**Issue by pogster** [MyUNiDAYS/unidays-php#16]
### Describe the bug

When I set an order total of larger than 999.99, the following error occurs:
`Exception: Notice: A non well formed numeric value encountered  in (...)/vendor/unidays/unidays-php/src/Unidays/tracking-helper.php on line 101 `

**To Reproduce**

This is my call, Magento 1 around it.
```
        $details = new Unidays\DirectTrackingDetailsBuilder($partnerId, $order->getIncrementId(), $order->getOrderCurrencyCode());
        $details->withOrderTotal($order->getGrandTotal());
        $details->withItemsUnidaysDiscount(abs($order->getDiscountAmount()));
        $details->withCode($order->getCouponCode());
        $details->withItemsGross($this->getItemsGross($order));
        $directTrackingDetails = $details->build();

        $client = new Unidays\TrackingClient($directTrackingDetails, $key);

        /** @var Httpful\Response $response */
        $response = $client->sendRequest();
```

**Reproduces how often:**

Every time.

**Expected behaviour**

No error.

**Additional context**

It seems the `DirectTrackingDetailsBuilder->withXy($number)` calls will execute `number_format($number, 2)` on the supplied values (turning them into 1,000.01 for example).
The `TrackingHelper` on `generate_query()` will then execute `urlencode(number_format($number, 2, '.', ','));` on the already formatted numbers. And number_format doesn't accept already formatted numbers.

**Comment by jackthorley** [comment]
Thank you for raising this issue @pogster. 

We will look to prioritise this issue; in the meantime, however, we would happily accept a PR with the changes for a quicker turnaround.

If that's the course of action you would like to take, please read our [contribution guidelines](https://github.com/MyUNiDAYS/unidays-php/blob/master/.github/contributing.md).

**Comment by pogster** [comment]
Made a PR.
