### ISSUE TITLE
Tag latest version

### ISSUE THREAD

**Issue by pogster** [MyUNiDAYS/unidays-php#20]
Hey,

I believe the latest tagged version is not up to date. Could you please make a tag of the current version?

Thanks,
Carsten

**Comment by Danny-UKDM** [comment]
Hi @pogster - I appreciate that this is an insanely late response, it appears that notifications for this repository haven't been reaching the relevant inbox.

In any case I've had a look into the tags on this repository and it does look like the latest version has been tagged correctly. 

May I ask what exactly has led you to believe that we are missing a tag for the latest version?

**Comment by pogster** [comment]
Hello Danny, to be honest I have no idea 2 years later. Thanks for your answer, I will close this.
